<!DOCTYPE html>
<html>

<head>
    <title>Demo | Browser notifications</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-cyan.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/app/home/home.css">
</head>

<body>

    <main class="app-content">
        <button disabled class="app-push-subscription-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
            Disable notifications
        </button>
        <div class="app-manage-push-messages-link-container">
            <a class="app-manage-push-messages-link" href="/admin">Manage notifications</a> 
        </div>
    </main>

    <script type="text/javascript" src="/app/home/home.js"></script>
</body>

</html>